project:
  type: website

website:
  title: "Automatic sigil"
  favicon: images/profile.jpg
  navbar:
    right:
      - about.qmd
  sidebar:
    style: "docked"
    contents:
      - section: "Rules"
        contents:
          - href: posts/core_rules_game/index.qmd
          - href: posts/core_rules_characters/index.qmd

format:
  html:
    theme: simplex
    css: styles.css



