project:
  type: website
  output-dir: docs

website:
  title: "Automatic sigil"
  favicon: images/profile.jpg
  navbar:
    right:
      - about.qmd
  sidebar:
    style: "docked"
    contents:
      - section: "Rules"
        contents:
          - href: posts/core_rules_game/index.qmd
          - href: posts/core_rules_characters/index.qmd
      - section: "Settings"
        contents:
          - href: posts/britannia_players/index.qmd
          - href: posts/britannia_referee/index.qmd
          - href: posts/alagaesia/hex_test.qmd
          - href: posts/middle_earth/index.qmd

format:
  html:
    theme: simplex
    css: styles.css

